/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudentLoginRouteImport } from './routes/student-login'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StaffIndexRouteImport } from './routes/staff.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as StudentTargetsRouteImport } from './routes/student.targets'
import { Route as StudentDashboardRouteImport } from './routes/student.dashboard'
import { Route as StaffDashboardRouteImport } from './routes/staff.dashboard'
import { Route as AdminTargetsRouteImport } from './routes/admin.targets'
import { Route as AdminTargetTemplatesRouteImport } from './routes/admin.target-templates'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminClassAssignmentsRouteImport } from './routes/admin.class-assignments'
import { Route as AdminAdmissionsRouteImport } from './routes/admin.admissions'
import { Route as AdminAcademicRouteImport } from './routes/admin.academic'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'

const StudentLoginRoute = StudentLoginRouteImport.update({
  id: '/student-login',
  path: '/student-login',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffIndexRoute = StaffIndexRouteImport.update({
  id: '/staff/',
  path: '/staff/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentTargetsRoute = StudentTargetsRouteImport.update({
  id: '/student/targets',
  path: '/student/targets',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentDashboardRoute = StudentDashboardRouteImport.update({
  id: '/student/dashboard',
  path: '/student/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffDashboardRoute = StaffDashboardRouteImport.update({
  id: '/staff/dashboard',
  path: '/staff/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTargetsRoute = AdminTargetsRouteImport.update({
  id: '/admin/targets',
  path: '/admin/targets',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTargetTemplatesRoute = AdminTargetTemplatesRouteImport.update({
  id: '/admin/target-templates',
  path: '/admin/target-templates',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminClassAssignmentsRoute = AdminClassAssignmentsRouteImport.update({
  id: '/admin/class-assignments',
  path: '/admin/class-assignments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdmissionsRoute = AdminAdmissionsRouteImport.update({
  id: '/admin/admissions',
  path: '/admin/admissions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAcademicRoute = AdminAcademicRouteImport.update({
  id: '/admin/academic',
  path: '/admin/academic',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mcp': typeof McpRoute
  '/student-login': typeof StudentLoginRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/academic': typeof AdminAcademicRoute
  '/admin/admissions': typeof AdminAdmissionsRoute
  '/admin/class-assignments': typeof AdminClassAssignmentsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/target-templates': typeof AdminTargetTemplatesRoute
  '/admin/targets': typeof AdminTargetsRoute
  '/staff/dashboard': typeof StaffDashboardRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/targets': typeof StudentTargetsRoute
  '/admin/': typeof AdminIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mcp': typeof McpRoute
  '/student-login': typeof StudentLoginRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/academic': typeof AdminAcademicRoute
  '/admin/admissions': typeof AdminAdmissionsRoute
  '/admin/class-assignments': typeof AdminClassAssignmentsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/target-templates': typeof AdminTargetTemplatesRoute
  '/admin/targets': typeof AdminTargetsRoute
  '/staff/dashboard': typeof StaffDashboardRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/targets': typeof StudentTargetsRoute
  '/admin': typeof AdminIndexRoute
  '/staff': typeof StaffIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mcp': typeof McpRoute
  '/student-login': typeof StudentLoginRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/academic': typeof AdminAcademicRoute
  '/admin/admissions': typeof AdminAdmissionsRoute
  '/admin/class-assignments': typeof AdminClassAssignmentsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/target-templates': typeof AdminTargetTemplatesRoute
  '/admin/targets': typeof AdminTargetsRoute
  '/staff/dashboard': typeof StaffDashboardRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/targets': typeof StudentTargetsRoute
  '/admin/': typeof AdminIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/mcp'
    | '/student-login'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/academic'
    | '/admin/admissions'
    | '/admin/class-assignments'
    | '/admin/dashboard'
    | '/admin/target-templates'
    | '/admin/targets'
    | '/staff/dashboard'
    | '/student/dashboard'
    | '/student/targets'
    | '/admin/'
    | '/staff/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/mcp'
    | '/student-login'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/academic'
    | '/admin/admissions'
    | '/admin/class-assignments'
    | '/admin/dashboard'
    | '/admin/target-templates'
    | '/admin/targets'
    | '/staff/dashboard'
    | '/student/dashboard'
    | '/student/targets'
    | '/admin'
    | '/staff'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
  id:
    | '__root__'
    | '/'
    | '/mcp'
    | '/student-login'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/academic'
    | '/admin/admissions'
    | '/admin/class-assignments'
    | '/admin/dashboard'
    | '/admin/target-templates'
    | '/admin/targets'
    | '/staff/dashboard'
    | '/student/dashboard'
    | '/student/targets'
    | '/admin/'
    | '/staff/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  McpRoute: typeof McpRoute
  StudentLoginRoute: typeof StudentLoginRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  AdminAcademicRoute: typeof AdminAcademicRoute
  AdminAdmissionsRoute: typeof AdminAdmissionsRoute
  AdminClassAssignmentsRoute: typeof AdminClassAssignmentsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminTargetTemplatesRoute: typeof AdminTargetTemplatesRoute
  AdminTargetsRoute: typeof AdminTargetsRoute
  StaffDashboardRoute: typeof StaffDashboardRoute
  StudentDashboardRoute: typeof StudentDashboardRoute
  StudentTargetsRoute: typeof StudentTargetsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  StaffIndexRoute: typeof StaffIndexRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/student-login': {
      id: '/student-login'
      path: '/student-login'
      fullPath: '/student-login'
      preLoaderRoute: typeof StudentLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/': {
      id: '/staff/'
      path: '/staff'
      fullPath: '/staff/'
      preLoaderRoute: typeof StaffIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/targets': {
      id: '/student/targets'
      path: '/student/targets'
      fullPath: '/student/targets'
      preLoaderRoute: typeof StudentTargetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/dashboard': {
      id: '/student/dashboard'
      path: '/student/dashboard'
      fullPath: '/student/dashboard'
      preLoaderRoute: typeof StudentDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/dashboard': {
      id: '/staff/dashboard'
      path: '/staff/dashboard'
      fullPath: '/staff/dashboard'
      preLoaderRoute: typeof StaffDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/targets': {
      id: '/admin/targets'
      path: '/admin/targets'
      fullPath: '/admin/targets'
      preLoaderRoute: typeof AdminTargetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/target-templates': {
      id: '/admin/target-templates'
      path: '/admin/target-templates'
      fullPath: '/admin/target-templates'
      preLoaderRoute: typeof AdminTargetTemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/class-assignments': {
      id: '/admin/class-assignments'
      path: '/admin/class-assignments'
      fullPath: '/admin/class-assignments'
      preLoaderRoute: typeof AdminClassAssignmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/admissions': {
      id: '/admin/admissions'
      path: '/admin/admissions'
      fullPath: '/admin/admissions'
      preLoaderRoute: typeof AdminAdmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/academic': {
      id: '/admin/academic'
      path: '/admin/academic'
      fullPath: '/admin/academic'
      preLoaderRoute: typeof AdminAcademicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  McpRoute: McpRoute,
  StudentLoginRoute: StudentLoginRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  AdminAcademicRoute: AdminAcademicRoute,
  AdminAdmissionsRoute: AdminAdmissionsRoute,
  AdminClassAssignmentsRoute: AdminClassAssignmentsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminTargetTemplatesRoute: AdminTargetTemplatesRoute,
  AdminTargetsRoute: AdminTargetsRoute,
  StaffDashboardRoute: StaffDashboardRoute,
  StudentDashboardRoute: StudentDashboardRoute,
  StudentTargetsRoute: StudentTargetsRoute,
  AdminIndexRoute: AdminIndexRoute,
  StaffIndexRoute: StaffIndexRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
