/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudentLoginRouteImport } from './routes/student-login'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as AdmissionRouteImport } from './routes/admission'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StaffIndexRouteImport } from './routes/staff.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as StudentTargetsRouteImport } from './routes/student.targets'
import { Route as StudentReportsRouteImport } from './routes/student.reports'
import { Route as StudentProfileRouteImport } from './routes/student.profile'
import { Route as StudentDashboardRouteImport } from './routes/student.dashboard'
import { Route as StudentCompetitionsRouteImport } from './routes/student.competitions'
import { Route as StudentAttendanceRouteImport } from './routes/student.attendance'
import { Route as StudentAnnouncementsRouteImport } from './routes/student.announcements'
import { Route as StaffDashboardRouteImport } from './routes/staff.dashboard'
import { Route as StaffCompetitionsRouteImport } from './routes/staff.competitions'
import { Route as StaffClassesRouteImport } from './routes/staff.classes'
import { Route as StaffCheckRequestsRouteImport } from './routes/staff.check-requests'
import { Route as StaffAttendanceRouteImport } from './routes/staff.attendance'
import { Route as StaffAnnouncementsRouteImport } from './routes/staff.announcements'
import { Route as AdminWebsiteRouteImport } from './routes/admin.website'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTargetsRouteImport } from './routes/admin.targets'
import { Route as AdminTargetTemplatesRouteImport } from './routes/admin.target-templates'
import { Route as AdminSystemRouteImport } from './routes/admin.system'
import { Route as AdminStudentsRouteImport } from './routes/admin.students'
import { Route as AdminStaffRouteImport } from './routes/admin.staff'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminCompetitionsRouteImport } from './routes/admin.competitions'
import { Route as AdminClassesRouteImport } from './routes/admin.classes'
import { Route as AdminClassAssignmentsRouteImport } from './routes/admin.class-assignments'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminAttendanceRouteImport } from './routes/admin.attendance'
import { Route as AdminAnnouncementsRouteImport } from './routes/admin.announcements'
import { Route as AdminAdmissionsRouteImport } from './routes/admin.admissions'
import { Route as AdminAcademicRouteImport } from './routes/admin.academic'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as StaffTermReportStudentIdRouteImport } from './routes/staff.term-report.$studentId'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'

const StudentLoginRoute = StudentLoginRouteImport.update({
  id: '/student-login',
  path: '/student-login',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionRoute = AdmissionRouteImport.update({
  id: '/admission',
  path: '/admission',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffIndexRoute = StaffIndexRouteImport.update({
  id: '/staff/',
  path: '/staff/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentTargetsRoute = StudentTargetsRouteImport.update({
  id: '/student/targets',
  path: '/student/targets',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentReportsRoute = StudentReportsRouteImport.update({
  id: '/student/reports',
  path: '/student/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentProfileRoute = StudentProfileRouteImport.update({
  id: '/student/profile',
  path: '/student/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentDashboardRoute = StudentDashboardRouteImport.update({
  id: '/student/dashboard',
  path: '/student/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentCompetitionsRoute = StudentCompetitionsRouteImport.update({
  id: '/student/competitions',
  path: '/student/competitions',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentAttendanceRoute = StudentAttendanceRouteImport.update({
  id: '/student/attendance',
  path: '/student/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentAnnouncementsRoute = StudentAnnouncementsRouteImport.update({
  id: '/student/announcements',
  path: '/student/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffDashboardRoute = StaffDashboardRouteImport.update({
  id: '/staff/dashboard',
  path: '/staff/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffCompetitionsRoute = StaffCompetitionsRouteImport.update({
  id: '/staff/competitions',
  path: '/staff/competitions',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffClassesRoute = StaffClassesRouteImport.update({
  id: '/staff/classes',
  path: '/staff/classes',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffCheckRequestsRoute = StaffCheckRequestsRouteImport.update({
  id: '/staff/check-requests',
  path: '/staff/check-requests',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffAttendanceRoute = StaffAttendanceRouteImport.update({
  id: '/staff/attendance',
  path: '/staff/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffAnnouncementsRoute = StaffAnnouncementsRouteImport.update({
  id: '/staff/announcements',
  path: '/staff/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWebsiteRoute = AdminWebsiteRouteImport.update({
  id: '/admin/website',
  path: '/admin/website',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTargetsRoute = AdminTargetsRouteImport.update({
  id: '/admin/targets',
  path: '/admin/targets',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTargetTemplatesRoute = AdminTargetTemplatesRouteImport.update({
  id: '/admin/target-templates',
  path: '/admin/target-templates',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSystemRoute = AdminSystemRouteImport.update({
  id: '/admin/system',
  path: '/admin/system',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStudentsRoute = AdminStudentsRouteImport.update({
  id: '/admin/students',
  path: '/admin/students',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStaffRoute = AdminStaffRouteImport.update({
  id: '/admin/staff',
  path: '/admin/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCompetitionsRoute = AdminCompetitionsRouteImport.update({
  id: '/admin/competitions',
  path: '/admin/competitions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminClassesRoute = AdminClassesRouteImport.update({
  id: '/admin/classes',
  path: '/admin/classes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminClassAssignmentsRoute = AdminClassAssignmentsRouteImport.update({
  id: '/admin/class-assignments',
  path: '/admin/class-assignments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAttendanceRoute = AdminAttendanceRouteImport.update({
  id: '/admin/attendance',
  path: '/admin/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnnouncementsRoute = AdminAnnouncementsRouteImport.update({
  id: '/admin/announcements',
  path: '/admin/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdmissionsRoute = AdminAdmissionsRouteImport.update({
  id: '/admin/admissions',
  path: '/admin/admissions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAcademicRoute = AdminAcademicRouteImport.update({
  id: '/admin/academic',
  path: '/admin/academic',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const StaffTermReportStudentIdRoute =
  StaffTermReportStudentIdRouteImport.update({
    id: '/staff/term-report/$studentId',
    path: '/staff/term-report/$studentId',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admission': typeof AdmissionRoute
  '/mcp': typeof McpRoute
  '/student-login': typeof StudentLoginRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/academic': typeof AdminAcademicRoute
  '/admin/admissions': typeof AdminAdmissionsRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/class-assignments': typeof AdminClassAssignmentsRoute
  '/admin/classes': typeof AdminClassesRoute
  '/admin/competitions': typeof AdminCompetitionsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/system': typeof AdminSystemRoute
  '/admin/target-templates': typeof AdminTargetTemplatesRoute
  '/admin/targets': typeof AdminTargetsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/website': typeof AdminWebsiteRoute
  '/staff/announcements': typeof StaffAnnouncementsRoute
  '/staff/attendance': typeof StaffAttendanceRoute
  '/staff/check-requests': typeof StaffCheckRequestsRoute
  '/staff/classes': typeof StaffClassesRoute
  '/staff/competitions': typeof StaffCompetitionsRoute
  '/staff/dashboard': typeof StaffDashboardRoute
  '/student/announcements': typeof StudentAnnouncementsRoute
  '/student/attendance': typeof StudentAttendanceRoute
  '/student/competitions': typeof StudentCompetitionsRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/reports': typeof StudentReportsRoute
  '/student/targets': typeof StudentTargetsRoute
  '/admin/': typeof AdminIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/staff/term-report/$studentId': typeof StaffTermReportStudentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admission': typeof AdmissionRoute
  '/mcp': typeof McpRoute
  '/student-login': typeof StudentLoginRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/academic': typeof AdminAcademicRoute
  '/admin/admissions': typeof AdminAdmissionsRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/class-assignments': typeof AdminClassAssignmentsRoute
  '/admin/classes': typeof AdminClassesRoute
  '/admin/competitions': typeof AdminCompetitionsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/system': typeof AdminSystemRoute
  '/admin/target-templates': typeof AdminTargetTemplatesRoute
  '/admin/targets': typeof AdminTargetsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/website': typeof AdminWebsiteRoute
  '/staff/announcements': typeof StaffAnnouncementsRoute
  '/staff/attendance': typeof StaffAttendanceRoute
  '/staff/check-requests': typeof StaffCheckRequestsRoute
  '/staff/classes': typeof StaffClassesRoute
  '/staff/competitions': typeof StaffCompetitionsRoute
  '/staff/dashboard': typeof StaffDashboardRoute
  '/student/announcements': typeof StudentAnnouncementsRoute
  '/student/attendance': typeof StudentAttendanceRoute
  '/student/competitions': typeof StudentCompetitionsRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/reports': typeof StudentReportsRoute
  '/student/targets': typeof StudentTargetsRoute
  '/admin': typeof AdminIndexRoute
  '/staff': typeof StaffIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/staff/term-report/$studentId': typeof StaffTermReportStudentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admission': typeof AdmissionRoute
  '/mcp': typeof McpRoute
  '/student-login': typeof StudentLoginRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/academic': typeof AdminAcademicRoute
  '/admin/admissions': typeof AdminAdmissionsRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/class-assignments': typeof AdminClassAssignmentsRoute
  '/admin/classes': typeof AdminClassesRoute
  '/admin/competitions': typeof AdminCompetitionsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/system': typeof AdminSystemRoute
  '/admin/target-templates': typeof AdminTargetTemplatesRoute
  '/admin/targets': typeof AdminTargetsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/website': typeof AdminWebsiteRoute
  '/staff/announcements': typeof StaffAnnouncementsRoute
  '/staff/attendance': typeof StaffAttendanceRoute
  '/staff/check-requests': typeof StaffCheckRequestsRoute
  '/staff/classes': typeof StaffClassesRoute
  '/staff/competitions': typeof StaffCompetitionsRoute
  '/staff/dashboard': typeof StaffDashboardRoute
  '/student/announcements': typeof StudentAnnouncementsRoute
  '/student/attendance': typeof StudentAttendanceRoute
  '/student/competitions': typeof StudentCompetitionsRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/reports': typeof StudentReportsRoute
  '/student/targets': typeof StudentTargetsRoute
  '/admin/': typeof AdminIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/staff/term-report/$studentId': typeof StaffTermReportStudentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admission'
    | '/mcp'
    | '/student-login'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/academic'
    | '/admin/admissions'
    | '/admin/announcements'
    | '/admin/attendance'
    | '/admin/audit'
    | '/admin/class-assignments'
    | '/admin/classes'
    | '/admin/competitions'
    | '/admin/dashboard'
    | '/admin/reports'
    | '/admin/staff'
    | '/admin/students'
    | '/admin/system'
    | '/admin/target-templates'
    | '/admin/targets'
    | '/admin/users'
    | '/admin/website'
    | '/staff/announcements'
    | '/staff/attendance'
    | '/staff/check-requests'
    | '/staff/classes'
    | '/staff/competitions'
    | '/staff/dashboard'
    | '/student/announcements'
    | '/student/attendance'
    | '/student/competitions'
    | '/student/dashboard'
    | '/student/profile'
    | '/student/reports'
    | '/student/targets'
    | '/admin/'
    | '/staff/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/staff/term-report/$studentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admission'
    | '/mcp'
    | '/student-login'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/academic'
    | '/admin/admissions'
    | '/admin/announcements'
    | '/admin/attendance'
    | '/admin/audit'
    | '/admin/class-assignments'
    | '/admin/classes'
    | '/admin/competitions'
    | '/admin/dashboard'
    | '/admin/reports'
    | '/admin/staff'
    | '/admin/students'
    | '/admin/system'
    | '/admin/target-templates'
    | '/admin/targets'
    | '/admin/users'
    | '/admin/website'
    | '/staff/announcements'
    | '/staff/attendance'
    | '/staff/check-requests'
    | '/staff/classes'
    | '/staff/competitions'
    | '/staff/dashboard'
    | '/student/announcements'
    | '/student/attendance'
    | '/student/competitions'
    | '/student/dashboard'
    | '/student/profile'
    | '/student/reports'
    | '/student/targets'
    | '/admin'
    | '/staff'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/staff/term-report/$studentId'
  id:
    | '__root__'
    | '/'
    | '/admission'
    | '/mcp'
    | '/student-login'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/academic'
    | '/admin/admissions'
    | '/admin/announcements'
    | '/admin/attendance'
    | '/admin/audit'
    | '/admin/class-assignments'
    | '/admin/classes'
    | '/admin/competitions'
    | '/admin/dashboard'
    | '/admin/reports'
    | '/admin/staff'
    | '/admin/students'
    | '/admin/system'
    | '/admin/target-templates'
    | '/admin/targets'
    | '/admin/users'
    | '/admin/website'
    | '/staff/announcements'
    | '/staff/attendance'
    | '/staff/check-requests'
    | '/staff/classes'
    | '/staff/competitions'
    | '/staff/dashboard'
    | '/student/announcements'
    | '/student/attendance'
    | '/student/competitions'
    | '/student/dashboard'
    | '/student/profile'
    | '/student/reports'
    | '/student/targets'
    | '/admin/'
    | '/staff/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/staff/term-report/$studentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdmissionRoute: typeof AdmissionRoute
  McpRoute: typeof McpRoute
  StudentLoginRoute: typeof StudentLoginRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  AdminAcademicRoute: typeof AdminAcademicRoute
  AdminAdmissionsRoute: typeof AdminAdmissionsRoute
  AdminAnnouncementsRoute: typeof AdminAnnouncementsRoute
  AdminAttendanceRoute: typeof AdminAttendanceRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminClassAssignmentsRoute: typeof AdminClassAssignmentsRoute
  AdminClassesRoute: typeof AdminClassesRoute
  AdminCompetitionsRoute: typeof AdminCompetitionsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminStaffRoute: typeof AdminStaffRoute
  AdminStudentsRoute: typeof AdminStudentsRoute
  AdminSystemRoute: typeof AdminSystemRoute
  AdminTargetTemplatesRoute: typeof AdminTargetTemplatesRoute
  AdminTargetsRoute: typeof AdminTargetsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminWebsiteRoute: typeof AdminWebsiteRoute
  StaffAnnouncementsRoute: typeof StaffAnnouncementsRoute
  StaffAttendanceRoute: typeof StaffAttendanceRoute
  StaffCheckRequestsRoute: typeof StaffCheckRequestsRoute
  StaffClassesRoute: typeof StaffClassesRoute
  StaffCompetitionsRoute: typeof StaffCompetitionsRoute
  StaffDashboardRoute: typeof StaffDashboardRoute
  StudentAnnouncementsRoute: typeof StudentAnnouncementsRoute
  StudentAttendanceRoute: typeof StudentAttendanceRoute
  StudentCompetitionsRoute: typeof StudentCompetitionsRoute
  StudentDashboardRoute: typeof StudentDashboardRoute
  StudentProfileRoute: typeof StudentProfileRoute
  StudentReportsRoute: typeof StudentReportsRoute
  StudentTargetsRoute: typeof StudentTargetsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  StaffIndexRoute: typeof StaffIndexRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  StaffTermReportStudentIdRoute: typeof StaffTermReportStudentIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/student-login': {
      id: '/student-login'
      path: '/student-login'
      fullPath: '/student-login'
      preLoaderRoute: typeof StudentLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admission': {
      id: '/admission'
      path: '/admission'
      fullPath: '/admission'
      preLoaderRoute: typeof AdmissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/': {
      id: '/staff/'
      path: '/staff'
      fullPath: '/staff/'
      preLoaderRoute: typeof StaffIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/targets': {
      id: '/student/targets'
      path: '/student/targets'
      fullPath: '/student/targets'
      preLoaderRoute: typeof StudentTargetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/reports': {
      id: '/student/reports'
      path: '/student/reports'
      fullPath: '/student/reports'
      preLoaderRoute: typeof StudentReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/profile': {
      id: '/student/profile'
      path: '/student/profile'
      fullPath: '/student/profile'
      preLoaderRoute: typeof StudentProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/dashboard': {
      id: '/student/dashboard'
      path: '/student/dashboard'
      fullPath: '/student/dashboard'
      preLoaderRoute: typeof StudentDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/competitions': {
      id: '/student/competitions'
      path: '/student/competitions'
      fullPath: '/student/competitions'
      preLoaderRoute: typeof StudentCompetitionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/attendance': {
      id: '/student/attendance'
      path: '/student/attendance'
      fullPath: '/student/attendance'
      preLoaderRoute: typeof StudentAttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/announcements': {
      id: '/student/announcements'
      path: '/student/announcements'
      fullPath: '/student/announcements'
      preLoaderRoute: typeof StudentAnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/dashboard': {
      id: '/staff/dashboard'
      path: '/staff/dashboard'
      fullPath: '/staff/dashboard'
      preLoaderRoute: typeof StaffDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/competitions': {
      id: '/staff/competitions'
      path: '/staff/competitions'
      fullPath: '/staff/competitions'
      preLoaderRoute: typeof StaffCompetitionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/classes': {
      id: '/staff/classes'
      path: '/staff/classes'
      fullPath: '/staff/classes'
      preLoaderRoute: typeof StaffClassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/check-requests': {
      id: '/staff/check-requests'
      path: '/staff/check-requests'
      fullPath: '/staff/check-requests'
      preLoaderRoute: typeof StaffCheckRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/attendance': {
      id: '/staff/attendance'
      path: '/staff/attendance'
      fullPath: '/staff/attendance'
      preLoaderRoute: typeof StaffAttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/announcements': {
      id: '/staff/announcements'
      path: '/staff/announcements'
      fullPath: '/staff/announcements'
      preLoaderRoute: typeof StaffAnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/website': {
      id: '/admin/website'
      path: '/admin/website'
      fullPath: '/admin/website'
      preLoaderRoute: typeof AdminWebsiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/targets': {
      id: '/admin/targets'
      path: '/admin/targets'
      fullPath: '/admin/targets'
      preLoaderRoute: typeof AdminTargetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/target-templates': {
      id: '/admin/target-templates'
      path: '/admin/target-templates'
      fullPath: '/admin/target-templates'
      preLoaderRoute: typeof AdminTargetTemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/system': {
      id: '/admin/system'
      path: '/admin/system'
      fullPath: '/admin/system'
      preLoaderRoute: typeof AdminSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/students': {
      id: '/admin/students'
      path: '/admin/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AdminStudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/staff': {
      id: '/admin/staff'
      path: '/admin/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AdminStaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/competitions': {
      id: '/admin/competitions'
      path: '/admin/competitions'
      fullPath: '/admin/competitions'
      preLoaderRoute: typeof AdminCompetitionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/classes': {
      id: '/admin/classes'
      path: '/admin/classes'
      fullPath: '/admin/classes'
      preLoaderRoute: typeof AdminClassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/class-assignments': {
      id: '/admin/class-assignments'
      path: '/admin/class-assignments'
      fullPath: '/admin/class-assignments'
      preLoaderRoute: typeof AdminClassAssignmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/attendance': {
      id: '/admin/attendance'
      path: '/admin/attendance'
      fullPath: '/admin/attendance'
      preLoaderRoute: typeof AdminAttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/announcements': {
      id: '/admin/announcements'
      path: '/admin/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AdminAnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/admissions': {
      id: '/admin/admissions'
      path: '/admin/admissions'
      fullPath: '/admin/admissions'
      preLoaderRoute: typeof AdminAdmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/academic': {
      id: '/admin/academic'
      path: '/admin/academic'
      fullPath: '/admin/academic'
      preLoaderRoute: typeof AdminAcademicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/term-report/$studentId': {
      id: '/staff/term-report/$studentId'
      path: '/staff/term-report/$studentId'
      fullPath: '/staff/term-report/$studentId'
      preLoaderRoute: typeof StaffTermReportStudentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdmissionRoute: AdmissionRoute,
  McpRoute: McpRoute,
  StudentLoginRoute: StudentLoginRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  AdminAcademicRoute: AdminAcademicRoute,
  AdminAdmissionsRoute: AdminAdmissionsRoute,
  AdminAnnouncementsRoute: AdminAnnouncementsRoute,
  AdminAttendanceRoute: AdminAttendanceRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminClassAssignmentsRoute: AdminClassAssignmentsRoute,
  AdminClassesRoute: AdminClassesRoute,
  AdminCompetitionsRoute: AdminCompetitionsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminStaffRoute: AdminStaffRoute,
  AdminStudentsRoute: AdminStudentsRoute,
  AdminSystemRoute: AdminSystemRoute,
  AdminTargetTemplatesRoute: AdminTargetTemplatesRoute,
  AdminTargetsRoute: AdminTargetsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminWebsiteRoute: AdminWebsiteRoute,
  StaffAnnouncementsRoute: StaffAnnouncementsRoute,
  StaffAttendanceRoute: StaffAttendanceRoute,
  StaffCheckRequestsRoute: StaffCheckRequestsRoute,
  StaffClassesRoute: StaffClassesRoute,
  StaffCompetitionsRoute: StaffCompetitionsRoute,
  StaffDashboardRoute: StaffDashboardRoute,
  StudentAnnouncementsRoute: StudentAnnouncementsRoute,
  StudentAttendanceRoute: StudentAttendanceRoute,
  StudentCompetitionsRoute: StudentCompetitionsRoute,
  StudentDashboardRoute: StudentDashboardRoute,
  StudentProfileRoute: StudentProfileRoute,
  StudentReportsRoute: StudentReportsRoute,
  StudentTargetsRoute: StudentTargetsRoute,
  AdminIndexRoute: AdminIndexRoute,
  StaffIndexRoute: StaffIndexRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  StaffTermReportStudentIdRoute: StaffTermReportStudentIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
